/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author INFO PC
 */
public class JFormaKryesore extends javax.swing.JFrame {

    /**
     * Creates new form JFormaKryesore
     */
    public JFormaKryesore() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnArtikujt = new javax.swing.JMenu();
        mnStoqet = new javax.swing.JMenu();
        mnFurnitoret = new javax.swing.JMenu();
        mnKonsumatoret = new javax.swing.JMenu();
        mnFaturat = new javax.swing.JMenu();
        mnStafi = new javax.swing.JMenu();
        mnPorosia = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnArtikujt.setText("Artikujt");
        mnArtikujt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnArtikujtMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnArtikujt);

        mnStoqet.setText("Stoqet");
        mnStoqet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnStoqetMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnStoqet);

        mnFurnitoret.setText("Furnitoret");
        mnFurnitoret.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnFurnitoretMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnFurnitoret);

        mnKonsumatoret.setText("Konsumatoret");
        mnKonsumatoret.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnKonsumatoretMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnKonsumatoret);

        mnFaturat.setText("Faturat");
        mnFaturat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnFaturatMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnFaturat);

        mnStafi.setText("Stafi");
        mnStafi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnStafiMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnStafi);

        mnPorosia.setText("Porosia");
        mnPorosia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnPorosiaMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnPorosia);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnArtikujtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnArtikujtMouseClicked
       Artikujt a=new Artikujt();
       a.setVisible(true);
    }//GEN-LAST:event_mnArtikujtMouseClicked

    private void mnStoqetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnStoqetMouseClicked
      Stoku s=new Stoku();
      s.setVisible(true);
    }//GEN-LAST:event_mnStoqetMouseClicked

    private void mnFurnitoretMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnFurnitoretMouseClicked
       Furnitoret f=new Furnitoret();
       f.setVisible(true);
    }//GEN-LAST:event_mnFurnitoretMouseClicked

    private void mnKonsumatoretMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnKonsumatoretMouseClicked
        Konsumatoret k=new Konsumatoret();
        k.setVisible(true);
    }//GEN-LAST:event_mnKonsumatoretMouseClicked

    private void mnFaturatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnFaturatMouseClicked
    Faturat f=new Faturat();
    f.setVisible(true);
    }//GEN-LAST:event_mnFaturatMouseClicked

    private void mnStafiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnStafiMouseClicked
    FormaStafi s=new FormaStafi();
    s.setVisible(true);
    }//GEN-LAST:event_mnStafiMouseClicked

    private void mnPorosiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnPorosiaMouseClicked
      Porosia  p=new Porosia();
      p.setVisible(true);
    }//GEN-LAST:event_mnPorosiaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFormaKryesore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFormaKryesore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFormaKryesore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFormaKryesore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFormaKryesore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnArtikujt;
    private javax.swing.JMenu mnFaturat;
    private javax.swing.JMenu mnFurnitoret;
    private javax.swing.JMenu mnKonsumatoret;
    private javax.swing.JMenu mnPorosia;
    private javax.swing.JMenu mnStafi;
    private javax.swing.JMenu mnStoqet;
    // End of variables declaration//GEN-END:variables
}
